spring:
  application:
    name: payment-service
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: payment_group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 8098
  servlet:
    context-path: /payment

services-url:
  user: ${USER_SERVICE_URL}
  channel: ${CHANNEL_SERVICE_URL}

utils:
  membership-fee: 30000

payment-gateway:
  momo:
    partner-code: ${MOMO_PARTNER_CODE:MOMO}
    access-key: ${MOMO_ACCESS_KEY:F8BBA842ECF85}
    secret-key: ${MOMO_SECRET:K951B6PE1waDMi640xX08PD3vg6EkVlz}
    endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api}
