spring:
  application:
    name: video-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1026MB
      max-request-size: 1026MB
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: video_group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
server:
  port: 8086
  servlet:
    context-path: /videos

services-url:
  user: ${USER_SERVICE_URL}
  channel: ${CHANNEL_SERVICE_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  dir-prefix: "vibio/videos"
  secure-url-expire-in: 2 # 2 hour
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG