server:
  port: 8080
api:
  prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowed-origin-patterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        #============================  Auth route ============================#
        - id: auth_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/auth/**
          filters:
            - StripPrefix=2
            - RewritePath=/auth/, /user/auth/
        #============================  Token route ============================#
        - id: token_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/token/**
          filters:
            - StripPrefix=2
            - RewritePath=/token/, /user/token/
        #============================  User route ============================#
        - id: user_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/user/**
          filters:
            - StripPrefix=2
            - AuthorizationFilter
        #============================  Channel public route ============================#
        - id: channel_public_route
          uri: ${services.channel-service}
          predicates:
            - Path= ${api.prefix}/channels/guest/**
          filters:
            - StripPrefix=2
            - RewritePath=/channels(?<segment>/?.*), /channels${segment}
        #============================  Channel route ============================#
        - id: channel_route
          uri: ${services.channel-service}
          predicates:
            - Path= ${api.prefix}/channels/**
          filters:
            - StripPrefix=2
            - RewritePath=/channels(?<segment>/?.*), /channels${segment}
            - AuthorizationFilter
        #============================  Video public route ============================#
        - id: video_public_route
          uri: ${services.video-service}
          predicates:
            - Path= ${api.prefix}/videos/guest/**
          filters:
            - StripPrefix=2
            - RewritePath=/videos(?<segment>/?.*), /videos${segment}
        #============================  Video route ============================#
        - id: video_route
          uri: ${services.video-service}
          predicates:
            - Path= ${api.prefix}/videos/**
          filters:
            - StripPrefix=2
            - RewritePath=/videos(?<segment>/?.*), /videos${segment}
            - AuthorizationFilter
        #============================  Notification route ============================#
        - id: notification_route
          uri: ${services.notification-service}
          predicates:
            - Path= ${api.prefix}/notification/**
          filters:
            - StripPrefix=2
            - RewritePath=/notification(?<segment>/?.*), /notification${segment}
            - AuthorizationFilter
        #============================  Payment route ============================#
        - id: payment_route
          uri: ${services.payment-service}
          predicates:
            - Path= ${api.prefix}/payment/**
          filters:
            - StripPrefix=2
            - RewritePath=/payment(?<segment>/?.*), /payment${segment}
            - AuthorizationFilter
        #============================  Search route ============================#
        - id: search_route
          uri: ${services.search-service}
          predicates:
            - Path= ${api.prefix}/search/**
          filters:
            - StripPrefix=2
            - RewritePath=/search(?<segment>/?.*), /search${segment}

services:
  user-service: ${USER_SERVICE_URL:http://localhost:8082}
  channel-service: ${CHANNEL_SERVICE_URL:http://localhost:8084}
  video-service: ${VIDEO_SERVICE_URL:http://localhost:8086}
  notification-service: ${NOTIFICATION_SERVICE:http://localhost:8088}
  payment-service: ${PAYMENT_SERVICE:http://localhost:8098}
  search-service: ${SEARCH_SERVICE:http://localhost:8088}