server:
  port: 8080
api:
  prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #        ======== AUTH ===========
        - id: auth_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/auth/**
          filters:
            - StripPrefix=2
            - RewritePath=/auth/, /user/auth/
        #        ======== TOKEN ===========
        - id: token_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/token/**
          filters:
            - StripPrefix=2
            - RewritePath=/token/, /user/token/
        #        ======== USER ===========
        - id: user_route
          uri: ${services.user-service}
          predicates:
            - Path= ${api.prefix}/user/**
          filters:
            - StripPrefix=2
            - AuthorizationFilter
        #        ======== CHANNEL ===========
        - id: channel_route
          uri: ${services.channel-service}
          predicates:
            - Path= ${api.prefix}/channel/**
          filters:
            - StripPrefix=2
            - AuthorizationFilter
        #        ======== VIDEO ===========
        - id: channel_route
          uri: ${services.video-service}
          predicates:
            - Path= ${api.prefix}/video/**
          filters:
            - StripPrefix=2

services:
  user-service: ${USER_SERVICE_URL}
  channel-service: ${CHANNEL_SERVICE_URL}
  video-service: ${VIDEO_SERVICE_URL}